trigger:
  - dev  

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git remote set-url github https://github.com/PedroCarvalho18/powebi.git
      git fetch github
      git checkout main
      git merge github/main
      git push origin main
    displayName: 'Sincronizando Azure DevOps com GitHub'
